version: '3.7'
services:
  booker_api:
    build: ../
    ports:
      - "5000:5000"
    depends_on: 
      - booker_db
  booker_db:
    build: ../database/
    ports:
      - "9999:5432"
    volumes:
      - ../database/.data:/var/lib/postgresql/data