version: '3.7'
services:
  api:
    build:
      context: ../
      dockerfile: scripts/docker/api/Dockerfile
    ports:
      - "5000:80"
    depends_on: 
      - db
    container_name: booker_api
  db:
    build: ../database/
    ports:
      - "9999:5432"
    volumes:
      - ../database/.data:/var/lib/postgresql/data
    container_name: booker_db